---
## https://docs.travis-ci.com/user/osx-ci-environment/
os:
  - osx

#language: python
#python: "2.7"
before_install:
  - sw_vers
  - uname -a
  - brew update
  - brew install libidn2
  - brew install openssl
  - brew upgrade openssl
  - brew ls --verbose openssl
  - brew install python3
  - brew update
  - brew doctor
  - python --version
#  - pip --version
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - python3 --version
  - python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
  - pip3 --version
#  - which pip
## error: could not create '/Library/Python/2.7/site-packages/ansible': Permission denied
#  - pip install ansible ansible-lint
#  - pip install --user ansible ansible-lint
  - env
  - find . -ls
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
#  - find $HOME/Library $HOME/.local -ls || true
  - openssl s_client -connect developers.yubico.com:443  -cipher 'ALL' < /dev/null || true
  - $(brew --prefix)/opt/openssl/bin/openssl s_client -connect developers.yubico.com:443  -cipher 'ALL' < /dev/null || true
## workaround to openssl mess
  - sudo install -d -o travis -m755 /private/var/_install
  - brew install curl
  - curl -o /private/var/_install/yubikey-piv-manager-1.4.2b-mac.pkg https://developers.yubico.com/yubikey-piv-manager/Releases/yubikey-piv-manager-1.4.2b-mac.pkg
  - curl -o /private/var/_install/yubico-piv-tool-1.4.3-mac.zip https://developers.yubico.com/yubico-piv-tool/Releases/yubico-piv-tool-1.4.3-mac.zip

install:
  - pip3 install ansible
  - ansible --version
  - which ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"

#  - "ansible-lint tasks/main.yml"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"

# Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i inventory --connection=local --become -vvvv test/integration/default/default.yml"

# Run the role/playbook again, checking to make sure it's idempotent.
## FIXME! known fail
  - "ansible-playbook -i inventory test/integration/default/default.yml --connection=local --become | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)"

  - "ls -A $HOME/"
  - "ls -A /Applications/"
