---
name: lint

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every monday 04:00
    - cron: '0 4 * * 1'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 4
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.macos_yubikey
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 --version
          python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
          python3 -c 'import ssl; ssl.PROTOCOL_TLSv1_2'
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          set -x
          which ansible || true
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
          echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.macos_yubikey
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callback_whitelist = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          pwd
          env
          find . -ls
      - name: yamllint
        run: |
          cd $GITHUB_WORKSPACE/juju4.macos_yubikey && yamllint .
      - name: ansible-lint
        run: |
          cd $GITHUB_WORKSPACE/juju4.macos_yubikey && ansible-lint
